name: Build
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: package install
      run: ./ci_prereq.sh

    - name: build
      run: ./ci_build.sh

    - name: test prerequisites
      run: ./ci_test_prereq.sh

    - name: test
      run: ./ci_test.sh
