name: Build
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: package install
      run: ./ci_prereq.sh

    - name: build
      run: ./ci_build.sh

    - name: test prerequisites
      run: ./ci_test_prereq.sh

    - name: test
      run: ./ci_test.sh

    - name: pages
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir -p pub/files
        zip --junk-paths pub/files/comcom64.zip build/src/comcom64.exe
        zip --junk-paths pub/files/comcom32.zip 32/comcom32.exe
        echo '<a href="files/comcom64.zip">Latest comcom64 build</a><br>' > pub/index.html
        echo '<a href="files/comcom32.zip">Latest comcom32 build</a><br>' >> pub/index.html

    - name: deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: pub
